default_language_version:
  python: python3.11
exclude: '.*\.run\.ipynb$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: debug-statements
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # This hook checks toml files for parseable syntax.
      - id: check-toml
      # This hook checks yaml files for parseable syntax.
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9025
    hooks:
      - id: style-files
  - repo: https://github.com/mwouts/jupytext
    rev: v1.15.2
    hooks:
      - id: jupytext
        entry: jupytext
        types_or: [ jupyter ]
        args: [ --sync ]
