name: manubot-ai-editor-code
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=8.*
  - jupyterlab=4.1.*
  - jupytext=1.15.2
  - langchain=0.1.*
  - matplotlib=3.8.*
  - nbconvert-core
  - numpy=1.26.*
  - openpyxl=3.1.*
  - pandas=2.2.*
  - papermill=2.5.*
  - pip
  - pre-commit=3.6.*
  - pytask=0.4.*
  - python=3.11.*
  - python-dotenv=1.0.*
  - pyyaml=6.*
  - ruff=0.3.3
  - scipy=1.12.*
  - seaborn=0.13.*
  - tqdm=4.*
  - pip:
      - langchain-openai
      - pygithub==2.2.*
